name: ci
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - run: yarn install
      - run: yarn run build:lib
      - run: sudo yarn run link
      - run: yarn run test
